### ISSUE TITLE
Having issues to setup this Bot

### ISSUE THREAD

**Issue by netdevilz** [ColumbiaSC-Tech/botty_mcbotface#41]
Hello,
I am missing something while setting up this bot. 
1) Created virtualenv
2) Create settings and run files
3) pip install botty-mcbotface
4) python run.py
 
It's throwing error can't import TIMEZONE from settings file.

Can you someone help please?

**Comment by netdevilz** [comment]
@DannyHinshaw Thanks for getting back. After adding TIMEZONE variable now it's throwing below error

```
(env) PS C:\Users\Zohaib\Desktop\newbot> python .\run.py
Traceback (most recent call last):
  File ".\run.py", line 4, in <module>
    from botty_mcbotface import log
  File "C:\Users\Zohaib\Desktop\newbot\env\lib\site-packages\botty_mcbotface\__init__.py", line 33, in <module>
    init_db()
  File "C:\Users\Zohaib\Desktop\newbot\env\lib\site-packages\botty_mcbotface\__init__.py", line 27, in init_db
    import botty_mcbotface.botty.db.routines
  File "C:\Users\Zohaib\Desktop\newbot\env\lib\site-packages\botty_mcbotface\botty\db\routines\__init__.py", line 1, in <module>
    from .routine_populate_db import *
  File "C:\Users\Zohaib\Desktop\newbot\env\lib\site-packages\botty_mcbotface\botty\db\routines\routine_populate_db.py", line 2, in <module>
    from botty_mcbotface.botty.api import get_all_channels, get_all_users
  File "C:\Users\Zohaib\Desktop\newbot\env\lib\site-packages\botty_mcbotface\botty\api.py", line 4, in <module>
    from run import bot
ImportError: cannot import name 'bot' from 'run' (C:\Users\Zohaib\Desktop\newbot\run.py)
(env) PS C:\Users\Zohaib\Desktop\newbot>
```

**Comment by DannyHinshaw** [comment]
That I am not sure of... what is your `run.py` contents and where did you place it?

**Comment by DannyHinshaw** [comment]
@netdevilz I see now, it's another literal undocumented feature

add:

```python
bot = Bot()
```

to your `run.py` file above the `main` definition.
